---
filepath: 'D:\Data\scenda\giocomo\npI5_0417_baseline_1.mat'
subject_id: 'L5'
subject_date_of_birth: 'April 4, 2016 12:15AM'
subject_description: 'wild-type'
subject_sex: 'Male'
subject_weight: '11.6g'
subject_species: 'Mouse'
subject_brain_region: 'Medial Entorhinal Cortex'
session_id: 'npI5_0417_baseline_1'
session_start_time: 'April 4, 2017 10:00AM'
experimenter: 'Kei Masuda'
experiment_description: 'Virtual Hallway Task'
institution: 'Stanford University School of Medicine'
lab_name: 'Giocomo Lab'
...
---
filepath: 'D:\Data\scenda\giocomo\npI5_0417_baseline_1_duplicate.mat'
subject_id: 'L5'
subject_date_of_birth: 'April 4, 2016 12:10AM'
subject_description: 'wild-type'
subject_sex: 'Male'
subject_weight: '11.6g'
subject_species: 'Mouse'
subject_brain_region: 'Medial Entorhinal Cortex'
session_id: 'npI5_0417_baseline_1'
session_start_time: 'April 4, 2017 10:00AM'
experimenter: 'Kei Masuda'
experiment_description: 'Virtual Hallway Task'
institution: 'Stanford University School of Medicine'
lab_name: 'Giocomo Lab'
...


